<?php


/**
 * Implements hook_permission().
 */
function media_entity_permission() {
  $perms = array(
    'administer media' => array(
      'title' => t('Administer media'),
      'restrict access' => TRUE,
    ),
    'view media' => array(
      'title' => t('View media'),
    ),
    'update media' => array(
      'title' => t('Update media'),
    ),
    'delete media' => array(
      'title' => t('Delete media'),
    ),
    'create media' => array(
      'title' => t('Create media'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_theme().
 */
function media_entity_theme() {
  return array(
    'media_add_list' => array(
      'variables' => array('content' => NULL),
      'file' => 'media_entity.pages.inc',
      'template' => 'media-add-list',
    ),
  );
}

/**
 * Implements hook_admin_paths().
 */
function media_entity_admin_paths() {
  $paths = array(
    'media/add' => TRUE,
    'media/add/*' => TRUE,
  );
  return $paths;
}
