<?php


/**
 * Implements hook_permission().
 */
function media_entity_permission() {
  $perms = array(
    'administer media' => array(
      'title' => t('Administer media'),
      'restrict access' => TRUE,
    ),
    'view media' => array(
      'title' => t('View media'),
    ),
    'update media' => array(
      'title' => t('Update media'),
    ),
    'delete media' => array(
      'title' => t('Delete media'),
    ),
    'create media' => array(
      'title' => t('Create media'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_menu_link_defaults().
 */
function media_entity_menu_link_defaults() {
  $items['media_entity.admin.structure.media'] = array(
    'link_title' => 'Media bundles',
    'description' => 'Manage media bundles, including field configuration, display configuration, etc.',
    'parent' => 'system.admin.structure',
    'route_name' => 'media.overview_bundles',
  );
  $items['media_entity.admin.content'] = array(
    'link title' => 'Add Media Bundle',
    'description' => 'Add a new Media object',
    'parent' => 'system.admin',
    'route_name' => 'media.add',
  );
  return $items;
}

/**
 * Loads a media entity from the database.
 *
 * @param int $mid
 *   The media ID.
 * @param bool $reset
 *   (optional) Whether to reset the media_load_multiple() cache. Defaults to
 *   FALSE.
 *
 * @return \Drupal\media_entity\MediaInterface|null
 *   A fully-populated media entity, or NULL if the media is not found.
 */
function media_entity_load($mid = NULL, $reset = FALSE) {
  return entity_load('media', $mid, $reset);
}

/**
 * Entity URI callback.
 *
 * @param \Drupal\media_entity\MediaInterface $media
 *   A media entity.
 *
 * @return array
 *   Route information array.
 */
function media_entity_uri(\Drupal\media_entity\MediaInterface $media) {
  return array(
    'route_name' => 'media.view',
    'route_parameters' => array(
      'media' => $media->id(),
    ),
  );
}

/**
 * Implements hook_entity_bundle_info().
 */
function media_entity_entity_bundle_info() {
  // @TODO: Do we want to cache this?
  $bundles = array();
  $config_names = \Drupal::configFactory()->listAll('media_entity.bundle.');
  foreach ($config_names as $config_name) {
    $config = \Drupal::config($config_name);
    $bundles['media'][$config->get('id')]['label'] = $config->get('label');
  }

  return $bundles;
}

/**
 * Implements hook_theme().
 */
function media_entity_theme() {
  return array(
    'media_add_list' => array(
      'variables' => array('content' => NULL),
      'file' => 'media_entity.pages.inc',
      'template' => 'media-add-list',
    ),
  );
}

/**
 * Implements hook_admin_paths().
 */
function media_entity_admin_paths() {
  $paths = array(
    'media/add' => TRUE,
    'media/add/*' => TRUE,
  );
  return $paths;
}
